spring.application.name=fake-info
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/addresses}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${SERVER_PORT:8081}
spring.jackson.default-property-inclusion=non_null
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.error.whitelabel.enabled=false
